<?php
/**
 * @file
 * Code for the GSB MSx Fellows Display feature.
 */

include_once 'gsb_feature_msx_fellows_display.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function gsb_feature_msx_fellows_display_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if ($form_state['view']->name == 'msx_fellows') {
    $form['#prefix'] = '<strong>' . t('Filter by') . '</strong>';
    $form['last_name']['#type'] = 'hidden';
  }
}

function gsb_feature_msx_fellows_display_gsb_fpp_customizations_icons_alter(&$icons) {
  $module_path = drupal_get_path('module', 'gsb_feature_msx_fellows_display');
  $icons_settings = array(
    'views_panes:msx_fellows-list' => 'MSx_fellows.png',        
  );
  foreach($icons_settings as $key => $value) {
    if (isset($icons[$key]['icon'])) {
      $icons[$key]['icon'] = $module_path . '/images/' . $value;
    }
  }
}
